import { type Challenge, type ChallengeParticipant } from '@/hooks/useChallenges';

const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();
const daysFromNow = (d: number) => new Date(Date.now() + d * 86400000).toISOString();

export const demoChallenges: Challenge[] = [
  {
    id: 'demo-ch-1',
    title: '100 Pushup Challenge',
    description: 'Complete 100 pushups in 7 days. Build chest and arm strength! 💪',
    exercise_type: 'pushups',
    target_reps: 100,
    duration_days: 7,
    is_global: true,
    global_target: 50000,
    created_at: daysAgo(2),
    ends_at: daysFromNow(5),
    participant_count: 342,
    global_progress: 28750,
  },
  {
    id: 'demo-ch-2',
    title: '500 Squats Week',
    description: 'Crush 500 squats this week! Your legs will thank you later 🦵',
    exercise_type: 'squats',
    target_reps: 500,
    duration_days: 7,
    is_global: false,
    global_target: null,
    created_at: daysAgo(1),
    ends_at: daysFromNow(6),
    participant_count: 189,
    global_progress: 0,
  },
  {
    id: 'demo-ch-3',
    title: '200 Sit-ups Sprint',
    description: 'Core strength challenge - 200 sit-ups in 5 days. Who\'s in? 🔥',
    exercise_type: 'situps',
    target_reps: 200,
    duration_days: 5,
    is_global: false,
    global_target: null,
    created_at: daysAgo(1),
    ends_at: daysFromNow(4),
    participant_count: 127,
    global_progress: 0,
  },
  {
    id: 'demo-ch-4',
    title: 'Global Plank Party 🌍',
    description: 'Together we plank! Community goal: 1 million seconds of plank holds worldwide.',
    exercise_type: 'plank',
    target_reps: 300,
    duration_days: 14,
    is_global: true,
    global_target: 1000000,
    created_at: daysAgo(3),
    ends_at: daysFromNow(11),
    participant_count: 1204,
    global_progress: 456200,
  },
  {
    id: 'demo-ch-5',
    title: 'Lunge Marathon',
    description: 'Can you hit 300 lunges in 10 days? Strengthen those legs! 🏃',
    exercise_type: 'lunges',
    target_reps: 300,
    duration_days: 10,
    is_global: false,
    global_target: null,
    created_at: daysAgo(2),
    ends_at: daysFromNow(8),
    participant_count: 95,
    global_progress: 0,
  },
  {
    id: 'demo-ch-6',
    title: 'Jumping Jacks Frenzy ⭐',
    description: 'Get your cardio in! 1000 jumping jacks in 14 days - easy peasy! 😤',
    exercise_type: 'jumping_jacks',
    target_reps: 1000,
    duration_days: 14,
    is_global: true,
    global_target: 500000,
    created_at: daysAgo(5),
    ends_at: daysFromNow(9),
    participant_count: 567,
    global_progress: 213000,
  },
  {
    id: 'demo-ch-7',
    title: 'Tricep Dip Destroyer',
    description: 'Build those triceps! 150 dips in a week 💎',
    exercise_type: 'tricep_dips',
    target_reps: 150,
    duration_days: 7,
    is_global: false,
    global_target: null,
    created_at: daysAgo(3),
    ends_at: daysFromNow(4),
    participant_count: 78,
    global_progress: 0,
  },
  {
    id: 'demo-ch-8',
    title: 'High Knees Hustle',
    description: 'Get those knees up! 500 high knees to boost your cardio game 🦿',
    exercise_type: 'high_knees',
    target_reps: 500,
    duration_days: 7,
    is_global: false,
    global_target: null,
    created_at: daysAgo(1),
    ends_at: daysFromNow(6),
    participant_count: 143,
    global_progress: 0,
  },
];

// Demo participations to show other "users" are active
export const demoParticipants: { challengeId: string; username: string; avatarUrl: string | null; progress: number; completed: boolean }[] = [
  // Pushup challenge
  { challengeId: 'demo-ch-1', username: 'fitness_priya', avatarUrl: null, progress: 100, completed: true },
  { challengeId: 'demo-ch-1', username: 'muscle_rahul', avatarUrl: null, progress: 87, completed: false },
  { challengeId: 'demo-ch-1', username: 'runner_vikram', avatarUrl: null, progress: 65, completed: false },
  { challengeId: 'demo-ch-1', username: 'yoga_anita', avatarUrl: null, progress: 45, completed: false },
  { challengeId: 'demo-ch-1', username: 'iron_arjun', avatarUrl: null, progress: 92, completed: false },
  // Squats
  { challengeId: 'demo-ch-2', username: 'muscle_rahul', avatarUrl: null, progress: 320, completed: false },
  { challengeId: 'demo-ch-2', username: 'power_neha', avatarUrl: null, progress: 410, completed: false },
  { challengeId: 'demo-ch-2', username: 'fitness_priya', avatarUrl: null, progress: 500, completed: true },
  // Sit-ups
  { challengeId: 'demo-ch-3', username: 'runner_vikram', avatarUrl: null, progress: 180, completed: false },
  { challengeId: 'demo-ch-3', username: 'core_king_sid', avatarUrl: null, progress: 200, completed: true },
  // Plank
  { challengeId: 'demo-ch-4', username: 'yoga_anita', avatarUrl: null, progress: 250, completed: false },
  { challengeId: 'demo-ch-4', username: 'fitness_priya', avatarUrl: null, progress: 300, completed: true },
  { challengeId: 'demo-ch-4', username: 'zen_maya', avatarUrl: null, progress: 180, completed: false },
  // Lunges
  { challengeId: 'demo-ch-5', username: 'muscle_rahul', avatarUrl: null, progress: 210, completed: false },
  { challengeId: 'demo-ch-5', username: 'runner_vikram', avatarUrl: null, progress: 300, completed: true },
  // Jumping Jacks
  { challengeId: 'demo-ch-6', username: 'cardio_queen_riya', avatarUrl: null, progress: 780, completed: false },
  { challengeId: 'demo-ch-6', username: 'iron_arjun', avatarUrl: null, progress: 1000, completed: true },
  { challengeId: 'demo-ch-6', username: 'yoga_anita', avatarUrl: null, progress: 540, completed: false },
  // Tricep dips
  { challengeId: 'demo-ch-7', username: 'power_neha', avatarUrl: null, progress: 120, completed: false },
  // High knees
  { challengeId: 'demo-ch-8', username: 'cardio_queen_riya', avatarUrl: null, progress: 350, completed: false },
  { challengeId: 'demo-ch-8', username: 'fitness_priya', avatarUrl: null, progress: 500, completed: true },
];
